// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using supai_mp.Data;

#nullable disable

namespace SUPAI_MP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907115528_AdicionarGruposEscala")]
    partial class AdicionarGruposEscala
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("supai_mp.Models.Ferias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataMarcacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRegistoFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRegistoInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Ferias");
                });

            modelBuilder.Entity("supai_mp.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Bi")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("C_Alternativo")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("C_Familiar")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Casa_N")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Contacto")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataIngresso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("FotografiaUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("G")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("LocalTrabalho")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nuit")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Quarterao_N")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int>("estado_civil")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("grauParentesco")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<int>("nivelAcademico")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Equipa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadeOperacionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("UnidadeOperacionalId");

                    b.ToTable("Equipas");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("PostoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostoId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("FuncionarioId", "Data", "HoraInicio");

                    b.ToTable("Escalas");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.FuncaoOperacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("FuncoesOperacionais");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.GrupoEscala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EquipaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OrdemRotacao")
                        .HasColumnType("int");

                    b.Property<int>("TipoTurnoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeOperacionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipaId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("UnidadeOperacionalId", "OrdemRotacao")
                        .IsUnique();

                    b.ToTable("GruposEscala");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.LotacaoFuncionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EquipaId")
                        .HasColumnType("int");

                    b.Property<int>("FuncaoOperacionalId")
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("PostoId")
                        .HasColumnType("int");

                    b.Property<int?>("SeccaoId")
                        .HasColumnType("int");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoTurnoId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadeOperacionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipaId");

                    b.HasIndex("FuncaoOperacionalId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("PostoId");

                    b.HasIndex("SeccaoId");

                    b.HasIndex("SectorId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("UnidadeOperacionalId");

                    b.ToTable("LotacoesFuncionarios");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Posto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SeccaoId")
                        .HasColumnType("int");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadeOperacionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("SeccaoId");

                    b.HasIndex("SectorId");

                    b.HasIndex("UnidadeOperacionalId");

                    b.ToTable("Postos");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Seccao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Seccoes");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("SeccaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeccaoId");

                    b.ToTable("Sectores");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.TipoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("HorasDescanso")
                        .HasColumnType("int");

                    b.Property<int>("HorasTrabalho")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TiposTurno");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.UnidadeOperacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("SeccaoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadePaiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeccaoId");

                    b.HasIndex("UnidadePaiId");

                    b.ToTable("UnidadesOperacionais");
                });

            modelBuilder.Entity("supai_mp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("supai_mp.Models.Ferias", b =>
                {
                    b.HasOne("supai_mp.Models.Funcionario", "Funcionario")
                        .WithMany("Ferias")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Equipa", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Sector", "Sector")
                        .WithMany("Equipas")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.UnidadeOperacional", "UnidadeOperacional")
                        .WithMany("Equipas")
                        .HasForeignKey("UnidadeOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sector");

                    b.Navigation("UnidadeOperacional");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Escala", b =>
                {
                    b.HasOne("supai_mp.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.Posto", "Posto")
                        .WithMany()
                        .HasForeignKey("PostoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Posto");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.GrupoEscala", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Equipa", "Equipa")
                        .WithMany()
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.UnidadeOperacional", "UnidadeOperacional")
                        .WithMany()
                        .HasForeignKey("UnidadeOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipa");

                    b.Navigation("TipoTurno");

                    b.Navigation("UnidadeOperacional");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.LotacaoFuncionario", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Equipa", "Equipa")
                        .WithMany("Lotacoes")
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.FuncaoOperacional", "FuncaoOperacional")
                        .WithMany("Lotacoes")
                        .HasForeignKey("FuncaoOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.Posto", "Posto")
                        .WithMany("Lotacoes")
                        .HasForeignKey("PostoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.Seccao", "Seccao")
                        .WithMany("Lotacoes")
                        .HasForeignKey("SeccaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.Sector", "Sector")
                        .WithMany("Lotacoes")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.UnidadeOperacional", "UnidadeOperacional")
                        .WithMany("Lotacoes")
                        .HasForeignKey("UnidadeOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Equipa");

                    b.Navigation("FuncaoOperacional");

                    b.Navigation("Funcionario");

                    b.Navigation("Posto");

                    b.Navigation("Seccao");

                    b.Navigation("Sector");

                    b.Navigation("TipoTurno");

                    b.Navigation("UnidadeOperacional");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Posto", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Seccao", "Seccao")
                        .WithMany("Postos")
                        .HasForeignKey("SeccaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.Sector", "Sector")
                        .WithMany("Postos")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.UnidadeOperacional", "UnidadeOperacional")
                        .WithMany("Postos")
                        .HasForeignKey("UnidadeOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Seccao");

                    b.Navigation("Sector");

                    b.Navigation("UnidadeOperacional");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Sector", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Seccao", "Seccao")
                        .WithMany("Sectores")
                        .HasForeignKey("SeccaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seccao");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.UnidadeOperacional", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Seccao", "Seccao")
                        .WithMany()
                        .HasForeignKey("SeccaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.UnidadeOperacional", "UnidadePai")
                        .WithMany("UnidadesFilhas")
                        .HasForeignKey("UnidadePaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Seccao");

                    b.Navigation("UnidadePai");
                });

            modelBuilder.Entity("supai_mp.Models.Usuario", b =>
                {
                    b.HasOne("supai_mp.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("supai_mp.Models.Funcionario", b =>
                {
                    b.Navigation("Ferias");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Equipa", b =>
                {
                    b.Navigation("Lotacoes");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.FuncaoOperacional", b =>
                {
                    b.Navigation("Lotacoes");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Posto", b =>
                {
                    b.Navigation("Lotacoes");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Seccao", b =>
                {
                    b.Navigation("Lotacoes");

                    b.Navigation("Postos");

                    b.Navigation("Sectores");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Sector", b =>
                {
                    b.Navigation("Equipas");

                    b.Navigation("Lotacoes");

                    b.Navigation("Postos");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.UnidadeOperacional", b =>
                {
                    b.Navigation("Equipas");

                    b.Navigation("Lotacoes");

                    b.Navigation("Postos");

                    b.Navigation("UnidadesFilhas");
                });
#pragma warning restore 612, 618
        }
    }
}
