// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using supai_mp.Data;

#nullable disable

namespace SUPAI_MP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261003215008_AssociarSeccoesAtuaisASUPAIMP")]
    partial class AssociarSeccoesAtuaisASUPAIMP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("supai_mp.Models.Ferias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataMarcacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRegistoFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRegistoInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Ferias");
                });

            modelBuilder.Entity("supai_mp.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Bi")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("C_Alternativo")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("C_Familiar")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Casa_N")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Contacto")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataIngresso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("FotografiaUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("G")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("LocalTrabalho")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nuit")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Quarterao_N")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int?>("SeccaoId")
                        .HasColumnType("int");

                    b.Property<int>("estado_civil")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("grauParentesco")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<int>("nivelAcademico")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeccaoId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.EntidadeInstitucional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Sigla")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("EntidadesInstitucionais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Comando Provincial da Polícia da República de Moçambique – Maputo",
                            Nome = "Comando Provincial da PRM – Maputo",
                            Sigla = "CPRM-Maputo"
                        });
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.PermissaoAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataConcessao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("TipoPermissaoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeInstitucionalId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoPermissaoId");

                    b.HasIndex("UnidadeInstitucionalId");

                    b.HasIndex("UsuarioId", "TipoPermissaoId", "UnidadeInstitucionalId")
                        .IsUnique();

                    b.ToTable("PermissoesAcesso");
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.TipoPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TiposPermissao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Codigo = "CONSULTAR_EFECTIVO",
                            Descricao = "Permite consultar a informação do efectivo da unidade autorizada.",
                            Nome = "Consultar Efectivo"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Codigo = "CONSULTAR_POSTOS",
                            Descricao = "Permite consultar a situação dos postos da unidade autorizada.",
                            Nome = "Consultar Postos"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Codigo = "CONSULTAR_SEGURANCA",
                            Descricao = "Permite consultar informação de situação de segurança autorizada.",
                            Nome = "Consultar Segurança"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Codigo = "CONSULTAR_RELATORIOS",
                            Descricao = "Permite consultar relatórios disponibilizados à unidade autorizada.",
                            Nome = "Consultar Relatórios"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Codigo = "CONSULTAR_ESCALAS",
                            Descricao = "Permite consultar escalas da unidade autorizada.",
                            Nome = "Consultar Escalas"
                        });
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.TipoUnidadeInstitucional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TiposUnidadeInstitucional");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Unidade institucional correspondente ao Comando Provincial.",
                            Nome = "Comando Provincial"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Subunidade institucional subordinada ao Comando Provincial.",
                            Nome = "Subunidade"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "Esquadra policial integrada na estrutura institucional.",
                            Nome = "Esquadra"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Posto policial integrado na estrutura institucional.",
                            Nome = "Posto"
                        });
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.UnidadeInstitucional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("EntidadeInstitucionalId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Sigla")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TipoUnidadeInstitucionalId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadePaiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoUnidadeInstitucionalId");

                    b.HasIndex("UnidadePaiId");

                    b.HasIndex("EntidadeInstitucionalId", "Nome")
                        .IsUnique();

                    b.ToTable("UnidadesInstitucionais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCadastro = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Comando Provincial da Polícia da República de Moçambique – Maputo.",
                            EntidadeInstitucionalId = 1,
                            Nome = "Comando Provincial da PRM – Maputo",
                            Sigla = "CPRM-Maputo",
                            TipoUnidadeInstitucionalId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCadastro = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Subunidade de Protecção de Altas Individualidades.",
                            EntidadeInstitucionalId = 1,
                            Nome = "SUPAI-MP",
                            Sigla = "SUPAI-MP",
                            TipoUnidadeInstitucionalId = 2,
                            UnidadePaiId = 1
                        });
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.UnidadeInstitucionalSeccao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("SeccaoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeInstitucionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeccaoId");

                    b.HasIndex("UnidadeInstitucionalId", "SeccaoId")
                        .IsUnique();

                    b.ToTable("UnidadesInstitucionaisSeccoes");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Equipa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadeOperacionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("UnidadeOperacionalId");

                    b.ToTable("Equipas");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EquipaId")
                        .HasColumnType("int");

                    b.Property<int>("FuncaoOperacionalId")
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("PostoId")
                        .HasColumnType("int");

                    b.Property<int?>("SeccaoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTurnoId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadeOperacionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipaId");

                    b.HasIndex("FuncaoOperacionalId");

                    b.HasIndex("PostoId");

                    b.HasIndex("SeccaoId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("UnidadeOperacionalId");

                    b.HasIndex("FuncionarioId", "Data", "HoraInicio");

                    b.ToTable("Escalas");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.FuncaoOperacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("FuncoesOperacionais");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.GrupoEscala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EquipaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OrdemRotacao")
                        .HasColumnType("int");

                    b.Property<int>("TipoTurnoId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeOperacionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipaId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("UnidadeOperacionalId", "OrdemRotacao")
                        .IsUnique();

                    b.ToTable("GruposEscala");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.LotacaoFuncionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EquipaId")
                        .HasColumnType("int");

                    b.Property<int>("FuncaoOperacionalId")
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("PostoId")
                        .HasColumnType("int");

                    b.Property<int?>("SeccaoId")
                        .HasColumnType("int");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoTurnoId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadeOperacionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipaId");

                    b.HasIndex("FuncaoOperacionalId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("PostoId");

                    b.HasIndex("SeccaoId");

                    b.HasIndex("SectorId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("UnidadeOperacionalId");

                    b.ToTable("LotacoesFuncionarios");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Posto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SeccaoId")
                        .HasColumnType("int");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadeOperacionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("SeccaoId");

                    b.HasIndex("SectorId");

                    b.HasIndex("UnidadeOperacionalId");

                    b.ToTable("Postos");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Seccao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Seccoes");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("SeccaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeccaoId");

                    b.ToTable("Sectores");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.TipoTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("HorasDescanso")
                        .HasColumnType("int");

                    b.Property<int>("HorasTrabalho")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TiposTurno");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.UnidadeOperacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("PostoId")
                        .HasColumnType("int");

                    b.Property<int>("SeccaoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadePaiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostoId");

                    b.HasIndex("SeccaoId");

                    b.HasIndex("UnidadePaiId");

                    b.ToTable("UnidadesOperacionais");
                });

            modelBuilder.Entity("supai_mp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UnidadeInstitucionalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("UnidadeInstitucionalId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("supai_mp.Models.Ferias", b =>
                {
                    b.HasOne("supai_mp.Models.Funcionario", "Funcionario")
                        .WithMany("Ferias")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("supai_mp.Models.Funcionario", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Seccao", "Seccao")
                        .WithMany("Funcionarios")
                        .HasForeignKey("SeccaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Seccao");
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.PermissaoAcesso", b =>
                {
                    b.HasOne("supai_mp.Models.Institucional.TipoPermissao", "TipoPermissao")
                        .WithMany("Permissoes")
                        .HasForeignKey("TipoPermissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Institucional.UnidadeInstitucional", "UnidadeInstitucional")
                        .WithMany()
                        .HasForeignKey("UnidadeInstitucionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoPermissao");

                    b.Navigation("UnidadeInstitucional");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.UnidadeInstitucional", b =>
                {
                    b.HasOne("supai_mp.Models.Institucional.EntidadeInstitucional", "EntidadeInstitucional")
                        .WithMany("Unidades")
                        .HasForeignKey("EntidadeInstitucionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Institucional.TipoUnidadeInstitucional", "TipoUnidadeInstitucional")
                        .WithMany("Unidades")
                        .HasForeignKey("TipoUnidadeInstitucionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Institucional.UnidadeInstitucional", "UnidadePai")
                        .WithMany("UnidadesFilhas")
                        .HasForeignKey("UnidadePaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EntidadeInstitucional");

                    b.Navigation("TipoUnidadeInstitucional");

                    b.Navigation("UnidadePai");
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.UnidadeInstitucionalSeccao", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Seccao", "Seccao")
                        .WithMany()
                        .HasForeignKey("SeccaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Institucional.UnidadeInstitucional", "UnidadeInstitucional")
                        .WithMany()
                        .HasForeignKey("UnidadeInstitucionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seccao");

                    b.Navigation("UnidadeInstitucional");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Equipa", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Sector", "Sector")
                        .WithMany("Equipas")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.UnidadeOperacional", "UnidadeOperacional")
                        .WithMany("Equipas")
                        .HasForeignKey("UnidadeOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sector");

                    b.Navigation("UnidadeOperacional");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Escala", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Equipa", "Equipa")
                        .WithMany()
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.FuncaoOperacional", "FuncaoOperacional")
                        .WithMany()
                        .HasForeignKey("FuncaoOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.Posto", "Posto")
                        .WithMany()
                        .HasForeignKey("PostoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.Seccao", "Seccao")
                        .WithMany()
                        .HasForeignKey("SeccaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.UnidadeOperacional", "UnidadeOperacional")
                        .WithMany()
                        .HasForeignKey("UnidadeOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Equipa");

                    b.Navigation("FuncaoOperacional");

                    b.Navigation("Funcionario");

                    b.Navigation("Posto");

                    b.Navigation("Seccao");

                    b.Navigation("TipoTurno");

                    b.Navigation("UnidadeOperacional");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.GrupoEscala", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Equipa", "Equipa")
                        .WithMany()
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.UnidadeOperacional", "UnidadeOperacional")
                        .WithMany()
                        .HasForeignKey("UnidadeOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipa");

                    b.Navigation("TipoTurno");

                    b.Navigation("UnidadeOperacional");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.LotacaoFuncionario", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Equipa", "Equipa")
                        .WithMany("Lotacoes")
                        .HasForeignKey("EquipaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.FuncaoOperacional", "FuncaoOperacional")
                        .WithMany("Lotacoes")
                        .HasForeignKey("FuncaoOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.Posto", "Posto")
                        .WithMany("Lotacoes")
                        .HasForeignKey("PostoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.Seccao", "Seccao")
                        .WithMany("Lotacoes")
                        .HasForeignKey("SeccaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.Sector", "Sector")
                        .WithMany("Lotacoes")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.TipoTurno", "TipoTurno")
                        .WithMany()
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.UnidadeOperacional", "UnidadeOperacional")
                        .WithMany("Lotacoes")
                        .HasForeignKey("UnidadeOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Equipa");

                    b.Navigation("FuncaoOperacional");

                    b.Navigation("Funcionario");

                    b.Navigation("Posto");

                    b.Navigation("Seccao");

                    b.Navigation("Sector");

                    b.Navigation("TipoTurno");

                    b.Navigation("UnidadeOperacional");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Posto", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Seccao", "Seccao")
                        .WithMany("Postos")
                        .HasForeignKey("SeccaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.Sector", "Sector")
                        .WithMany("Postos")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.UnidadeOperacional", "UnidadeOperacional")
                        .WithMany("Postos")
                        .HasForeignKey("UnidadeOperacionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Seccao");

                    b.Navigation("Sector");

                    b.Navigation("UnidadeOperacional");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Sector", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Seccao", "Seccao")
                        .WithMany("Sectores")
                        .HasForeignKey("SeccaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seccao");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.UnidadeOperacional", b =>
                {
                    b.HasOne("supai_mp.Models.Organizacao.Posto", "Posto")
                        .WithMany("UnidadesInternas")
                        .HasForeignKey("PostoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Organizacao.Seccao", "Seccao")
                        .WithMany()
                        .HasForeignKey("SeccaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("supai_mp.Models.Organizacao.UnidadeOperacional", "UnidadePai")
                        .WithMany("UnidadesFilhas")
                        .HasForeignKey("UnidadePaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Posto");

                    b.Navigation("Seccao");

                    b.Navigation("UnidadePai");
                });

            modelBuilder.Entity("supai_mp.Models.Usuario", b =>
                {
                    b.HasOne("supai_mp.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("supai_mp.Models.Institucional.UnidadeInstitucional", "UnidadeInstitucional")
                        .WithMany()
                        .HasForeignKey("UnidadeInstitucionalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Funcionario");

                    b.Navigation("UnidadeInstitucional");
                });

            modelBuilder.Entity("supai_mp.Models.Funcionario", b =>
                {
                    b.Navigation("Ferias");
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.EntidadeInstitucional", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.TipoPermissao", b =>
                {
                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.TipoUnidadeInstitucional", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("supai_mp.Models.Institucional.UnidadeInstitucional", b =>
                {
                    b.Navigation("UnidadesFilhas");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Equipa", b =>
                {
                    b.Navigation("Lotacoes");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.FuncaoOperacional", b =>
                {
                    b.Navigation("Lotacoes");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Posto", b =>
                {
                    b.Navigation("Lotacoes");

                    b.Navigation("UnidadesInternas");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Seccao", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("Lotacoes");

                    b.Navigation("Postos");

                    b.Navigation("Sectores");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.Sector", b =>
                {
                    b.Navigation("Equipas");

                    b.Navigation("Lotacoes");

                    b.Navigation("Postos");
                });

            modelBuilder.Entity("supai_mp.Models.Organizacao.UnidadeOperacional", b =>
                {
                    b.Navigation("Equipas");

                    b.Navigation("Lotacoes");

                    b.Navigation("Postos");

                    b.Navigation("UnidadesFilhas");
                });
#pragma warning restore 612, 618
        }
    }
}
